# src/main/resources/application.yml
kakao:
  pay:
    host: https://kapi.kakao.com
    admin-key: c9281302567c5f479d960d7d718065ca # 실제 발급받은 관리자 키
    cid: TC0ONETIME                # 가맹점 코드 (테스트용), 코드 작성 X ❌
    ready-path: /payment/ready      # 카카오페이 호출 주소, 코드 작성 X ❌
    approve-path: /payment/approve  # 카카오페이 인증 주소, 코드 작성 X ❌